package policy

import (
	"strings"

	"github.com/hironow/sightjack/internal/domain"
)

// strictnessRank returns a numeric rank for ordering: higher = stricter.
func strictnessRank(level domain.StrictnessLevel) int {
	switch level {
	case domain.StrictnessFog:
		return 0
	case domain.StrictnessAlert:
		return 1
	case domain.StrictnessLockdown:
		return 2
	default:
		return 0
	}
}

// ResolveStrictness determines the effective strictness level for a set of keys.
// Keys typically include the cluster name followed by Linear issue labels.
// Matching is case-insensitive. Resolution uses 3-layer max():
//
//	base = default
//	base = max(base, matched estimated values)
//	base = max(base, matched override values)
//
// Strictness can only go up, never down.
// The estimated parameter comes from ComputedConfig.EstimatedStrictness.
func ResolveStrictness(cfg domain.StrictnessConfig, estimated map[string]domain.StrictnessLevel, labels []string) domain.StrictnessLevel {
	base := cfg.Default

	// Layer 1: Check estimated (auto-generated by scan)
	for _, label := range labels {
		lower := strings.ToLower(label)
		for key, level := range estimated {
			if strings.ToLower(key) == lower {
				if strictnessRank(level) > strictnessRank(base) {
					base = level
				}
			}
		}
	}

	// Layer 2: Check overrides (manual, always wins if stronger)
	for _, label := range labels {
		lower := strings.ToLower(label)
		for key, level := range cfg.Overrides {
			if strings.ToLower(key) == lower {
				if strictnessRank(level) > strictnessRank(base) {
					base = level
				}
			}
		}
	}

	return base
}
