package domain

import (
	"time"

	"github.com/google/uuid"
)

// ImprovementTask represents a minimal task generated by the immediate layer
// when a corrective action is needed. It captures what to do, who should do it,
// and when the task expires.
type ImprovementTask struct {
	ID              string
	SourceEvent     string      // triggering event or D-Mail name
	TargetAgent     string      // which tool should act (sightjack/paintress/amadeus)
	SuggestedAction string      // what to do
	FailureType     FailureType // classification from the failure taxonomy
	Severity        Severity
	ExpiresAt       time.Time
	CreatedAt       time.Time
}

// NewImprovementTask creates a task with a unique ID and computed expiry.
func NewImprovementTask(sourceEvent, targetAgent, action string, ft FailureType, sev Severity, ttl time.Duration) ImprovementTask {
	now := time.Now().UTC()
	return ImprovementTask{
		ID:              uuid.New().String(),
		SourceEvent:     sourceEvent,
		TargetAgent:     targetAgent,
		SuggestedAction: action,
		FailureType:     ft,
		Severity:        sev,
		ExpiresAt:       now.Add(ttl),
		CreatedAt:       now,
	}
}

// Expired returns true if the task's validity window has passed.
func (t ImprovementTask) Expired() bool {
	return time.Now().UTC().After(t.ExpiresAt)
}
